from flask import Flask, render_template, request, send_file
import numpy as np
import pandas as pd
import joblib
import os
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

app = Flask(__name__)



model = joblib.load("models/credit_model.pkl")
scaler = joblib.load("models/scaler.pkl")


df = pd.read_csv("data/german_credit_data.csv")
comparison = pd.read_csv("outputs/model_comparison.csv")
comparison_table = comparison.to_html(
    classes="table table-striped",
    index=False
)
dataset_size = len(df)
feature_count = len(df.columns) - 1

best_model_name = "Random Forest"


with open("models/accuracy.txt", "r") as f:
    model_accuracy = f.read()


last_prediction = {}



@app.route("/")
def home():

    
    return render_template(
        "index.html",
        dataset_size=dataset_size,
        feature_count=feature_count,
        model_accuracy=model_accuracy,
        best_model_name=best_model_name
    )


@app.route("/predict", methods=["POST"])
def predict():
    
    global last_prediction

    features = [

        float(request.form["laufkont"]),
        float(request.form["laufzeit"]),
        float(request.form["moral"]),
        float(request.form["verw"]),
        float(request.form["hoehe"]),
        float(request.form["sparkont"]),
        float(request.form["beszeit"]),
        float(request.form["rate"]),
        float(request.form["famges"]),
        float(request.form["buerge"]),
        float(request.form["wohnzeit"]),
        float(request.form["verm"]),
        float(request.form["alter"]),
        float(request.form["weitkred"]),
        float(request.form["wohn"]),
        float(request.form["bishkred"]),
        float(request.form["beruf"]),
        float(request.form["pers"]),
        float(request.form["telef"]),
        float(request.form["gastarb"])

    ]

    data = np.array(features).reshape(1, -1)

    data = scaler.transform(data)

    prediction = model.predict(data)[0]

    probability = model.predict_proba(data)[0][1]

    confidence = round(probability * 100, 2)

    if prediction == 1:

        result = "✅ APPROVED"

        message = (
            "Customer has a good credit profile and "
            "is likely to repay the loan successfully."
        )

    else:

        result = "❌ REJECTED"

        message = (
            "Customer has a higher probability of "
            "defaulting on the loan."
        )


    history = {
        "Date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "Prediction": result,
        "Confidence": confidence
    }

    history_df = pd.DataFrame([history])

    history_file = "prediction_history.csv"

    if os.path.exists(history_file):
        history_df.to_csv(
            history_file,
            mode="a",
            header=False,
            index=False
        )
    else:
        history_df.to_csv(
            history_file,
            index=False
        )



    last_prediction = {

        "Prediction": result,
        "Confidence": f"{confidence}%",
        "Message": message,
        "Model": best_model_name,
        "Accuracy": f"{model_accuracy}%",
        "Date": datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    }

    return render_template(
        "index.html",
        prediction=result,
        confidence=confidence,
        message=message,
        dataset_size=dataset_size,
        feature_count=feature_count,
        model_accuracy=model_accuracy,
        best_model_name=best_model_name
    )



@app.route("/download-report")
def download_report():

    os.makedirs("reports", exist_ok=True)

    pdf_path = "reports/credit_report.pdf"

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    story = []

    
    story.append(Paragraph(
        "<font size=22><b>Credit Scoring Prediction Report</b></font>",
        styles["Title"]
    ))

    story.append(Paragraph("<br/><br/>", styles["BodyText"]))

    story.append(Paragraph("<b>Generated By:</b> Credit Scoring System", styles["BodyText"]))
    story.append(Paragraph("<b>Developer:</b> Ashish Kumar", styles["BodyText"]))
    story.append(Paragraph("<b>Date:</b> " + last_prediction["Date"], styles["BodyText"]))

    story.append(Paragraph("<br/><br/>", styles["BodyText"]))

    story.append(Paragraph("<font size=18><b>Prediction Summary</b></font>", styles["Heading2"]))

    story.append(Paragraph("<br/>", styles["BodyText"]))

    story.append(Paragraph(f"<b>Prediction:</b> {last_prediction['Prediction']}", styles["BodyText"]))

    story.append(Paragraph(f"<b>Confidence:</b> {last_prediction['Confidence']}", styles["BodyText"]))

    story.append(Paragraph(f"<b>Model Used:</b> {last_prediction['Model']}", styles["BodyText"]))

    story.append(Paragraph(f"<b>Model Accuracy:</b> {last_prediction['Accuracy']}", styles["BodyText"]))

    story.append(Paragraph("<br/>", styles["BodyText"]))

    story.append(Paragraph("<font size=18><b>Recommendation</b></font>", styles["Heading2"]))

    story.append(Paragraph(last_prediction["Message"], styles["BodyText"]))

    story.append(Paragraph("<br/><br/>", styles["BodyText"]))

    story.append(
        Paragraph(
            "<b>Note:</b> This prediction is generated using a Machine Learning model "
            "and should be used as a decision-support tool.",
            styles["Italic"]
        )
    )

    doc.build(story)

    return send_file(pdf_path, as_attachment=True)



if __name__ == "__main__":
    app.run(debug=True, port=5002)
